package me.mrhakan.agalarhack.docs;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import me.mrhakan.agalarhack.managers.Settings;
import me.mrhakan.agalarhack.module.Category;
import me.mrhakan.agalarhack.module.Module;

/**
 * Renders the module reference from the modules themselves.
 *
 * <p>Hand-written module documentation is wrong within one commit of being written: someone changes a
 * default, renames a setting or adds a module, and the page keeps confidently describing what used to
 * be true. Generating it from the live settings registry means the page is either correct or the
 * build fails, and there is no third state where it is quietly stale.
 *
 * <p>Lives in the test source set because its only consumer is the guard test: nothing in the client
 * reads it at runtime, and putting it in main would be shipping code on the chance someone wires it
 * up later.
 *
 * <p>The settings every module shares — the keybind, the HUD toggle, the favourite flag — are omitted
 * on purpose. Repeating them 48 times would bury the settings that are actually specific to a module,
 * which is the only reason to read the page.
 */
public final class ModuleDocs {
    private ModuleDocs() { }

    /** Registered on every module by {@code Module.registerSettings}; documented once, not per module. */
    public static final List<String> SHARED_SETTINGS =
            List.of("enabled", "keybind", "keyModifiers", "showInHud", "favorite", "lastUsed");

    private static final String HEADER = """
            # Module reference

            <!-- Generated by ModuleDocs from the modules' own settings. Do not edit by hand.
                 ModuleDocsTest fails when this file and the code disagree, and rewrites the file as
                 it fails, so the fix is to run the tests and commit the result. -->

            Every module also has the shared settings `enabled`, `keybind`, `keyModifiers`,
            `showInHud`, `favorite` and `lastUsed`, which are not repeated below.

            **UNTESTED** marks a module that has never been exercised in a running game. It compiles and
            its logic is unit tested; nobody has confirmed it behaves correctly in Minecraft.
            """;

    /**
     * @param modules any set of modules with {@code registerSettings()} already called
     * @return the complete markdown page, grouped by category and stably ordered
     */
    public static String render(List<Module> modules) {
        Map<String, List<Module>> byCategory = new TreeMap<>();
        for (Module module : modules) {
            String category = module.getCategory() == null ? "Uncategorised" : module.getCategory().name;
            byCategory.computeIfAbsent(category, key -> new ArrayList<>()).add(module);
        }

        StringBuilder page = new StringBuilder(HEADER);
        page.append(summary(modules, byCategory));
        for (var entry : byCategory.entrySet()) {
            page.append("\n## ").append(entry.getKey()).append("\n");
            List<Module> sorted = new ArrayList<>(entry.getValue());
            sorted.sort(Comparator.comparing(Module::getName, String.CASE_INSENSITIVE_ORDER));
            for (Module module : sorted) renderModule(page, module);
        }
        return page.toString();
    }

    private static String summary(List<Module> modules, Map<String, List<Module>> byCategory) {
        long untested = modules.stream().filter(Module::isExperimental).count();
        return "\n" + modules.size() + " modules across " + byCategory.size() + " categories; "
                + untested + " marked UNTESTED.\n";
    }

    private static void renderModule(StringBuilder page, Module module) {
        page.append("\n### ").append(module.getName());
        if (module.isExperimental()) page.append(" — UNTESTED");
        page.append("\n\n");
        String description = module.getDescription();
        page.append(description == null || description.isBlank() ? "_No description._" : description).append("\n");

        List<Settings.SettingSpec> specs = module.settings.getSpecs().stream()
                .filter(spec -> !SHARED_SETTINGS.contains(spec.getName()))
                .toList();
        if (specs.isEmpty()) {
            page.append("\nNo settings of its own.\n");
            return;
        }
        page.append("\n| Setting | Default | Values | Description |\n");
        page.append("| --- | --- | --- | --- |\n");
        for (Settings.SettingSpec spec : specs) {
            page.append("| `").append(spec.getName()).append("` | ")
                    .append(code(defaultText(spec))).append(" | ")
                    .append(code(spec.getConstraintText())).append(" | ")
                    .append(text(spec.getDescription())).append(" |\n");
        }
    }

    private static String defaultText(Settings.SettingSpec spec) {
        Object value = spec.getDefaultValue();
        if (value == null) return "";
        if (value instanceof Number number) {
            double raw = number.doubleValue();
            if (raw == Math.rint(raw) && !Double.isInfinite(raw)) return String.valueOf((long) raw);
            return String.valueOf(raw);
        }
        return String.valueOf(value);
    }

    private static String code(String raw) {
        return raw == null || raw.isBlank() ? "—" : "`" + escape(raw) + "`";
    }

    private static String text(String raw) {
        return raw == null || raw.isBlank() ? "—" : escape(raw);
    }

    /** A pipe or newline in a description would silently break the table row it lands in. */
    private static String escape(String raw) {
        return raw.replace("|", "\\|").replace("\n", " ").replace("\r", " ").trim();
    }
}
